프로젝트 루트 확인과 4개 CSV 불러오기

 

35. 프로젝트 루트 설정

In [64]:
# 35. 프로젝트 루트 설정

from pathlib import Path

project_root = Path.cwd()

if project_root.name == "notebooks":

    project_root = project_root.parent

data_dir = project_root / "data" / "raw"

print("프로젝트 루트:", project_root)

print("데이터 폴더:", data_dir)

print("데이터 폴더 존재:", data_dir.exists())

프로젝트 루트: c:\dev\ai-data-analysis-repository
데이터 폴더: c:\dev\ai-data-analysis-repository\data\raw
데이터 폴더 존재: True

### 프로젝트 폴더와 데이터 폴더 위치 찾기

이 코드는 **현재 내가 작업하고 있는 프로젝트의 위치를 확인하고, CSV 파일이 들어있는 `data/raw` 폴더를 찾아가는 코드**이다.

쉽게 말하면,

> "내 프로젝트 폴더가 어디에 있고, 데이터가 들어있는 폴더가 실제로 존재하는지 확인해 주세요."

라는 뜻이다.

---

#### 1. `Path` 가져오기

`from pathlib import Path`

Python에서 **폴더와 파일의 위치(경로)를 쉽게 다룰 수 있게 해주는 `Path` 기능을 가져온다.**

예를 들어,

`C:\dev\ai-project\data\raw`

같은 복잡한 폴더 위치를 Python에서 편하게 다룰 수 있게 해준다.

---

#### 2. 현재 작업 위치 확인하기

`project_root = Path.cwd()`

`cwd`는 **Current Working Directory**, 즉 **현재 작업 중인 폴더**라는 뜻이다.

따라서 이 코드는

> "Python아, 내가 지금 어느 폴더에서 작업하고 있는지 알려줘."

라는 의미이다.

그리고 그 위치를 `project_root`라는 변수에 저장한다.

---

#### 3. 현재 위치가 notebooks 폴더인지 확인하기

`if project_root.name == "notebooks":`

현재 작업하고 있는 폴더의 이름이 `notebooks`인지 확인한다.

예를 들어 현재 위치가

`ai-project/notebooks`

라면 조건이 참(True)이 된다.

---

#### 4. notebooks에 있다면 한 단계 위로 이동하기

`project_root = project_root.parent`

현재 위치가 `notebooks`라면 한 단계 위에 있는 **프로젝트 전체 폴더**로 이동한다.

예를 들어,

`ai-project/notebooks`

에서

`ai-project`

로 이동하는 것이다.

즉, `.parent`는 쉽게 말해서

> **"상위 폴더로 한 칸 올라가기"**

라고 이해하면 된다.

---

#### 5. 데이터 폴더 위치 만들기

`data_dir = project_root / "data" / "raw"`

프로젝트 폴더 안에 있는

`data → raw`

폴더의 위치를 만든다.

예를 들어 프로젝트 위치가

`C:\dev\ai-project`

라면 최종적으로

`C:\dev\ai-project\data\raw`

를 가리키게 된다.

여기에는 분석에 사용할 CSV 원본 데이터가 들어있다.

---

#### 6. 프로젝트 위치 출력하기

`print("프로젝트 루트:", project_root)`

현재 프로그램이 프로젝트의 가장 기본이 되는 폴더를 어디라고 판단했는지 출력한다.

---

#### 7. 데이터 폴더 위치 출력하기

`print("데이터 폴더:", data_dir)`

CSV 데이터가 들어있는 `data/raw` 폴더의 위치를 출력한다.

---

#### 8. 데이터 폴더가 실제로 존재하는지 확인하기

`print("데이터 폴더 존재:", data_dir.exists())`

`.exists()`는 해당 폴더가 **실제로 존재하는지 확인하는 기능**이다.

결과가

`True`

이면 데이터 폴더가 실제로 존재한다는 뜻이다.

반대로

`False`

가 나오면 경로가 잘못되었거나 해당 폴더가 없는지 확인해야 한다.

---

### 전체 흐름

현재 작업 위치 확인  
↓  
현재 위치가 `notebooks`인지 확인  
↓  
`notebooks`라면 상위 프로젝트 폴더로 이동  
↓  
`data/raw` 폴더 위치 만들기  
↓  
폴더가 실제로 존재하는지 확인

---

### 한 줄 정리

**현재 프로젝트의 위치를 찾고, 분석에 사용할 CSV 파일이 들어있는 `data/raw` 폴더가 실제로 존재하는지 확인하는 코드이다.**

# 36. pandas와 CSV 불러오기

In [65]:

import pandas as pd

customers = pd.read_csv(data_dir / "customers.csv")
products = pd.read_csv(data_dir / "products.csv")
orders = pd.read_csv(data_dir / "orders.csv")
order_items = pd.read_csv(data_dir / "order_items.csv")

# 37. 기본 구조와 주요 키 확인

In [66]:
datasets = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "order_items": order_items,

}

for name, df in datasets.items():

    print(name, df.shape, df.columns.tolist())

customers (150, 6) ['customer_id', 'name', 'gender', 'age', 'city', 'signup_date']
products (100, 4) ['product_id', 'product_name', 'category', 'price']
orders (300, 5) ['order_id', 'customer_id', 'order_date', 'payment_method', 'order_status']
order_items (764, 5) ['order_item_id', 'order_id', 'product_id', 'quantity', 'unit_price']

In [67]:

key_checks = {

    "customers.customer_id": customers["customer_id"],
    "products.product_id": products["product_id"],
    "orders.order_id": orders["order_id"],
    "order_items.order_item_id": order_items["order_item_id"],

}

for name, series in key_checks.items():
    print(
        name,
        "결측:", series.isna().sum(),
        "중복:", series.duplicated().sum(),
    )

customers.customer_id 결측: 0 중복: 0
products.product_id 결측: 0 중복: 0
orders.order_id 결측: 0 중복: 0
order_items.order_item_id 결측: 0 중복: 0

Part 10. 컬럼 선택·조건 필터링·정렬

 

38. Series와 DataFrame 선택

In [68]:
city_series = customers["city"]
customer_view = customers[
    ["customer_id", "gender", "age", "city"]
]
print(type(city_series))
print(type(customer_view))
display(customer_view.head())

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

   customer_id gender  age city
0            1      F   19   광주
1            2      F   32   대구
2            3      F   61   성남
3            4      F   55   울산
4            5      F   19   부산

39. 단일 조건 필터링

In [69]:
 
customers_over_30 = customers[
    customers["age"] >= 30
]
print(len(customers), len(customers_over_30))
display(customers_over_30.head())

150 111

   customer_id name gender  age city signup_date
1            2  김정호      F   32   대구  2025-11-30
2            3  이경수      F   61   성남  2024-07-10
3            4  조영호      F   55   울산  2026-05-11
5            6  김지원      F   32   성남  2026-07-25
6            7  이상현      F   53   인천  2025-01-09

40. 복합 조건 필터링

In [70]:

seoul_over_30 = customers[
    (customers["age"] >= 30)
    & (customers["city"] == "서울")

]

display(seoul_over_30.head())

    customer_id name gender  age city signup_date
8             9  송지민      M   69   서울  2025-11-16
14           15  장정식      M   69   서울  2026-07-02
29           30  이민재      F   32   서울  2023-08-11
47           48  김예은      F   47   서울  2025-04-29
65           66  김재호      F   39   서울  2025-12-31

In [71]:
seoul_or_busan = customers[
    customers["city"].isin(["서울", "부산"])
]

display(
    seoul_or_busan["city"].value_counts()
)

city
부산    16
서울    15
Name: count, dtype: int64

In [72]:

not_completed = orders[
    ~(orders["order_status"] == "completed")
]
display(
    not_completed["order_status"].value_counts(
        dropna=False
    )
)

order_status
cancelled    64
refunded     52
Name: count, dtype: int64

41. 상품 가격 정렬

In [73]:
expensive_products = (

    products
    .sort_values("price", ascending=False)
    .head(10)
)
display(
    expensive_products[
        [
            "product_id",
            "product_name",
            "category",
            "price",
        ]
    ]

)

    product_id product_name category   price
98          99    뷰티 상품 099       뷰티  200000
69          70    패션 상품 070       패션  198000
57          58    식품 상품 058       식품  197000
42          43    뷰티 상품 043       뷰티  197000
23          24   스포츠 상품 024      스포츠  196000
8            9   스포츠 상품 009      스포츠  193000
36          37    뷰티 상품 037       뷰티  193000
71          72    뷰티 상품 072       뷰티  189000
7            8   스포츠 상품 008      스포츠  189000
52          53  생활용품 상품 053     생활용품  188000

Part 11. line_total 생성과 전체 주문 금액 구분

 

42. 작업용 복사본과 파생 컬럼

In [74]:

order_items_work = order_items.copy()
order_items_work["line_total"] = (
    order_items_work["quantity"]
    * order_items_work["unit_price"]

_IncompleteInputError: incomplete input (763737766.py, line 4)

In [ ]:

display(

    order_items_work[

        [

            "order_item_id",

            "order_id",

            "product_id",

            "quantity",

            "unit_price",

            "line_total",

        ]

    ].head()
)

   order_item_id  order_id  product_id  quantity  unit_price  line_total
0              1         1         100         3      102000      306000
1              2         1          87         5       25000      125000
2              3         1           7         3      142000      426000
3              4         1           9         3      193000      579000
4              5         2          72         4      189000      756000

43. 수작업 검증

In [ ]:
sample = order_items_work.iloc[0]

expected = sample["quantity"] * sample["unit_price"]

actual = sample["line_total"]

print("수작업:", expected)

print("파생 컬럼:", actual)

print("일치:", expected == actual)

수작업: 306000
파생 컬럼: 306000
일치: True

In [75]:
#44. 전체 주문상세 금액
all_order_amount = order_items_work["line_total"].sum()
print("전체 주문상세 금액:", all_order_amount)

전체 주문상세 금액: 255610000

In [76]:
#45. 병합용 주문 컬럼 선택

orders_for_merge = orders[
    [
        "order_id",
        "customer_id",
        "order_date",
        "order_status",
    ]

].copy()

print(orders_for_merge.shape)
print(orders_for_merge.head())

(300, 4)
   order_id  customer_id  order_date order_status
0         1          123  2026-06-04    completed
1         2           77  2025-08-20    cancelled
2         3          138  2025-12-17    cancelled
3         4           57  2026-02-27    cancelled
4         5          125  2026-01-18    cancelled

In [77]:
#46. 주문상세와 주문 병합

order_sales = (
    order_items_work
    .merge(
        orders_for_merge,
        on="order_id",
        how="left",
        validate="many_to_one",
        indicator="order_match",
    )
)

In [78]:
#47. 병합 검증

print("병합 전 행 수:", len(order_items_work))
print("병합 후 행 수:", len(order_sales))
display(
    order_sales["order_match"].value_counts(
        dropna=False
    )
)

병합 전 행 수: 764
병합 후 행 수: 764

order_match
both          764
left_only       0
right_only      0
Name: count, dtype: int64

In [80]:
#미매칭 확인:
unmatched_orders = order_sales[
    order_sales["order_match"] != "both"
]
display(unmatched_orders.head())

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, unit_price, line_total, customer_id, order_date, order_status, order_match]
Index: []

In [81]:
#48. 완료 주문 분석셋
display(
    order_sales["order_status"].value_counts(
        dropna=False
    )
)

order_status
completed    474
cancelled    162
refunded     128
Name: count, dtype: int64

In [82]:

completed_sales = order_sales[
    order_sales["order_status"] == "completed"
].copy()

In [86]:
print("완료 주문상세 행:", len(completed_sales))
print("완료 주문 수:",
    completed_sales["order_id"].nunique(),
)

print("완료 주문 고객 수:",
    completed_sales["customer_id"].nunique(),
)

print("완료 주문 매출:",
    completed_sales["line_total"].sum(),
)

완료 주문상세 행: 474
완료 주문 수: 184
완료 주문 고객 수: 100
완료 주문 매출: 148990000

In [87]:
#49. 필요한 상품 정보만 선택

products_for_merge = products[
    ["product_id",
        "product_name",
        "category",]
].copy()
print(products_for_merge.head())

   product_id product_name category
0           1  전자기기 상품 001     전자기기
1           2    도서 상품 002       도서
2           3  전자기기 상품 003     전자기기
3           4  생활용품 상품 004     생활용품
4           5    식품 상품 005       식품

In [88]:
#50. 완료 주문상세와 상품 병합

completed_items = (

    completed_sales
    .merge(
        products_for_merge,
        on="product_id",
        how="left",
        validate="many_to_one",
        indicator="product_match",
    )
)

In [89]:
print(len(completed_sales), len(completed_items))
display(
    completed_items["product_match"].value_counts(
        dropna=False
    )
)

474 474

product_match
both          474
left_only       0
right_only      0
Name: count, dtype: int64

In [90]:
category_sales = (
    completed_items
    .groupby("category", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
        quantity_sold=("quantity", "sum"),
        detail_row_count=("order_item_id", "count"),
    )
    .sort_values("total_sales", ascending=False)
)
display(category_sales)

,category,total_sales,order_count,customer_count,quantity_sold,detail_row_count
3,스포츠,31743000,85,67,295,100
5,전자기기,26400000,60,44,259,78
2,생활용품,23915000,65,50,272,83
1,뷰티,23383000,65,53,223,76
4,식품,16573000,36,31,133,42
0,도서,16389000,52,46,149,58
6,패션,10587000,33,27,111,37

In [91]:
#52. 카테고리 합계 검증
category_total = category_sales["total_sales"].sum()
completed_total = completed_items["line_total"].sum()
print(category_total)
print(completed_total)
print(category_total == completed_total)

148990000
148990000
True

In [92]:
#53. 상품별 매출

product_sales = (
    completed_items
    .groupby(
        ["product_id", "product_name", "category"],
        as_index=False,
    )
    .agg(
        total_sales=("line_total", "sum"),
        quantity_sold=("quantity", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
    )
    .sort_values("total_sales", ascending=False)
)
display(product_sales.head(10))

,product_id,product_name,category,total_sales,quantity_sold,order_count,customer_count
39,41,스포츠 상품 041,스포츠,5705000,35,12,11
11,12,식품 상품 012,식품,4375000,25,7,7
8,9,스포츠 상품 009,스포츠,3860000,20,6,5
70,72,뷰티 상품 072,뷰티,3780000,20,6,6
69,71,전자기기 상품 071,전자기기,3703000,23,5,5
66,68,스포츠 상품 068,스포츠,3640000,26,8,8
78,81,전자기기 상품 081,전자기기,3630000,22,6,6
10,11,패션 상품 011,패션,3565000,31,7,7
20,22,생활용품 상품 022,생활용품,3248000,29,8,8
86,89,생활용품 상품 089,생활용품,3090000,30,11,11

In [93]:
#54. 주문 날짜 변환과 주문 월 생성

completed_items["order_date"] = pd.to_datetime(
    completed_items["order_date"],
    errors="coerce",
)
print(
    "날짜 변환 실패:",
    completed_items["order_date"].isna().sum(),
)

날짜 변환 실패: 0

In [95]:
completed_items.info

<bound method DataFrame.info of      order_item_id  order_id  product_id  quantity  unit_price  line_total  \
0                1         1         100         3      102000      306000
1                2         1          87         5       25000      125000
2                3         1           7         3      142000      426000
3                4         1           9         3      193000      579000
4               13         6          83         3       24000       72000
..             ...       ...         ...       ...         ...         ...
469            758       296          40         1      174000      174000
470            759       297          20         5       80000      400000
471            760       297          42         4       28000      112000
472            762       299           8         2      189000      378000
473            763       299          12         4      175000      700000

     customer_id order_date order_status order_match product_name category  \
0            123 2026-06-04    completed        both    도서 상품 100       도서
1            123 2026-06-04    completed        both    도서 상품 087       도서
2            123 2026-06-04    completed        both    도서 상품 007       도서
3            123 2026-06-04    completed        both   스포츠 상품 009      스포츠
4             87 2026-04-18    completed        both  전자기기 상품 083     전자기기
..           ...        ...          ...         ...          ...      ...
469          116 2026-03-02    completed        both    도서 상품 040       도서
470           22 2026-02-12    completed        both   스포츠 상품 020      스포츠
471           22 2026-02-12    completed        both    패션 상품 042       패션
472          135 2025-09-05    completed        both   스포츠 상품 008      스포츠
473          135 2025-09-05    completed        both    식품 상품 012       식품

    product_match order_month
0            both     2026-06
1            both     2026-06
2            both     2026-06
3            both     2026-06
4            both     2026-04
..            ...         ...
469          both     2026-03
470          both     2026-02
471          both     2026-02
472          both     2025-09
473          both     2025-09

[474 rows x 14 columns]>

In [94]:

completed_items["order_month"] = (
    completed_items["order_date"]
    .dt.to_period("M")
    .astype("string")
)

In [100]:
completed_items.head()

,order_item_id,order_id,product_id,quantity,unit_price,line_total,customer_id,order_date,order_status,order_match,product_name,category,product_match,order_month
0,1,1,100,3,102000,306000,123,2026-06-04,completed,both,도서 상품 100,도서,both,2026-06
1,2,1,87,5,25000,125000,123,2026-06-04,completed,both,도서 상품 087,도서,both,2026-06
2,3,1,7,3,142000,426000,123,2026-06-04,completed,both,도서 상품 007,도서,both,2026-06
3,4,1,9,3,193000,579000,123,2026-06-04,completed,both,스포츠 상품 009,스포츠,both,2026-06
4,13,6,83,3,24000,72000,87,2026-04-18,completed,both,전자기기 상품 083,전자기기,both,2026-04

In [101]:
#55. 월별 매출
monthly_sales = (
    completed_items
    .groupby("order_month", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        customer_count=("customer_id", "nunique"),
        quantity_sold=("quantity", "sum"),
    )
    .sort_values("order_month")
)
display(monthly_sales)

   order_month  total_sales  order_count  customer_count  quantity_sold
0      2025-08      5869000            8               8             52
1      2025-09     16147000           19              19            132
2      2025-10     12385000           15              15            120
3      2025-11     23550000           24              23            233
4      2025-12      9876000           13              13             99
5      2026-01     10851000           13              13            105
6      2026-02     16504000           21              20            150
7      2026-03      9885000           18              16            102
8      2026-04     15536000           17              16            157
9      2026-05     15310000           19              18            152
10     2026-06      9026000           12              12            102
11     2026-07      3128000            4               4             29
12     2026-08       923000            1               1              9

In [102]:
#56. 고객별 구매 금액

customer_sales = (
    completed_items
    .groupby("customer_id", as_index=False)
    .agg(
        total_sales=("line_total", "sum"),
        order_count=("order_id", "nunique"),
        quantity_sold=("quantity", "sum"),
    )
)

In [103]:
print(customer_sales.head())

   customer_id  total_sales  order_count  quantity_sold
0            3      3178000            2             26
1            4       603000            1              6
2            5      2004000            2             13
3            6      1349000            2             14
4            7      1173000            1              9

In [104]:
top10_customers = (
    customer_sales
    .sort_values("total_sales", ascending=False)
    .head(10)
)
display(top10_customers)

    customer_id  total_sales  order_count  quantity_sold
76          117      4100000            5             48
62          102      3996000            4             35
51           83      3880000            4             39
21           30      3590000            5             32
29           40      3523000            4             27
13           20      3191000            2             25
0             3      3178000            2             26
70          111      3153000            3             38
42           66      3093000            4             30
97          147      2990000            2             21

In [108]:
print(customer_sales.sort_values("total_sales", ascending=False)

)

    customer_id  total_sales  order_count  quantity_sold
76          117      4100000            5             48
62          102      3996000            4             35
51           83      3880000            4             39
21           30      3590000            5             32
29           40      3523000            4             27
..          ...          ...          ...            ...
33           49       262000            1              6
10           15       252000            1              2
44           69       130000            2              8
50           80       118000            1              2
71          112       112000            2              8

[100 rows x 4 columns]

In [110]:
customer_attributes = customers[
    ["customer_id", "gender", "age", "city"]
].copy()

In [111]:
customer_sales_detail = (
    customer_sales
    .merge(
        customer_attributes,
        on="customer_id",
        how="left",
        validate="one_to_one",
        indicator="customer_match",
    )
    .sort_values("total_sales", ascending=False)
)

In [113]:
display(
    customer_sales_detail["customer_match"].value_counts(
        dropna=False
    )
)
display(customer_sales_detail.head(10))

customer_match
both          100
left_only       0
right_only      0
Name: count, dtype: int64

,customer_id,total_sales,order_count,quantity_sold,gender,age,city,customer_match
76,117,4100000,5,48,F,65,성남,both
62,102,3996000,4,35,M,60,고양,both
51,83,3880000,4,39,F,22,수원,both
21,30,3590000,5,32,F,32,서울,both
29,40,3523000,4,27,M,23,서울,both
13,20,3191000,2,25,F,20,인천,both
0,3,3178000,2,26,F,61,성남,both
70,111,3153000,3,38,F,41,광주,both
42,66,3093000,4,30,F,39,서울,both
97,147,2990000,2,21,M,19,부산,both

In [115]:
#58. 결과 폴더 생성
output_dir = project_root / "reports" / "chapter04"
output_dir.mkdir(parents=True, exist_ok=True)
print(output_dir)

c:\dev\ai-data-analysis-repository\reports\chapter04

In [116]:
#59. 결과 파일 저장
outputs = {
    "category_sales.csv": category_sales,
    "product_sales.csv": product_sales,
    "monthly_sales.csv": monthly_sales,
    "customer_sales.csv": customer_sales_detail,
}
for file_name, df in outputs.items():
    output_path = output_dir / file_name
    df.to_csv(
        output_path,
        index=False,
        encoding="utf-8-sig",
    )
    print(
        file_name,
        output_path.exists(),
        output_path.stat().st_size,
    )

category_sales.csv True 309
product_sales.csv True 4833
monthly_sales.csv True 415
customer_sales.csv True 3448

In [117]:
#60. 저장 결과 다시 읽기
saved_category_sales = pd.read_csv(
    output_dir / "category_sales.csv"
)
display(saved_category_sales.head())
print(saved_category_sales.shape)

,category,total_sales,order_count,customer_count,quantity_sold,detail_row_count
0,스포츠,31743000,85,67,295,100
1,전자기기,26400000,60,44,259,78
2,생활용품,23915000,65,50,272,83
3,뷰티,23383000,65,53,223,76
4,식품,16573000,36,31,133,42

(7, 6)

In [118]:
#61. 병합 점검 함수
def check_merge_result(
    *,
    name: str,
    left_rows: int,
    merged: pd.DataFrame,
    indicator_column: str,
) -> None:
    print(f"[{name}]")
    print("병합 전 행 수:", left_rows)
    print("병합 후 행 수:", len(merged))
    print(
        merged[indicator_column].value_counts(
            dropna=False
        )
    )

In [119]:
check_merge_result(
    name="주문상세-주문",
    left_rows=len(order_items_work),
    merged=order_sales,
    indicator_column="order_match",
)

[주문상세-주문]
병합 전 행 수: 764
병합 후 행 수: 764
order_match
both          764
left_only       0
right_only      0
Name: count, dtype: int64

In [120]:
#62. 집계 합계 검증 함수
def check_total(
    *,
    name: str,
    source_total: float,
    summary_total: float,
) -> None:
    difference = source_total - summary_total
    print(f"[{name}]")
    print("원본 합계:", source_total)
    print("요약 합계:", summary_total)
    print("차이:", difference)

In [121]:
check_total(
    name="카테고리별 매출",
    source_total=completed_items["line_total"].sum(),
    summary_total=category_sales["total_sales"].sum(),
)

[카테고리별 매출]
원본 합계: 148990000
요약 합계: 148990000
차이: 0

In [122]:
completed_orders = orders[
    orders["order_status"] == "completed"
].copy()

In [123]:
completed_orders.head()

    order_id  customer_id  order_date payment_method order_status
0          1          123  2026-06-04           card    completed
5          6           87  2026-04-18      naver_pay    completed
8          9          145  2026-02-17           card    completed
10        11           47  2025-12-15           card    completed
11        12           98  2025-08-09      kakao_pay    completed

In [124]:
completed_orders["order_status"].value_counts()

order_status
completed    184
Name: count, dtype: int64

In [125]:
completed_items = order_items.merge(
    completed_orders,
    on="order_id",
    how="inner",
    validate="many_to_one",
    indicator=True
)

In [126]:
completed_items["_merge"].value_counts()

_merge
both          474
left_only       0
right_only      0
Name: count, dtype: int64

In [127]:
print("병합 전 order_items 행 수:", len(order_items))
print("완료 주문만 병합한 후 행 수:", len(completed_items))

병합 전 order_items 행 수: 764
완료 주문만 병합한 후 행 수: 474

In [ ]:
ompleted_items = completed_items.drop(columns="_merge")
completed_items = completed_items.merge(
    products,
    on="product_id",
    how="left",
    validate="many_to_one",
    indicator=True)c

### completed_items와 products 데이터 연결하기

이 코드는 **완료된 주문 상품 데이터에 상품 정보를 붙이는 코드**이다.

쉽게 말하면,

> "이 주문에 들어있는 product_id가 어떤 상품이고, 어떤 카테고리인지 찾아서 붙여주세요."

라는 뜻이다.

---

#### 1. 기존 `_merge` 컬럼 삭제

`completed_items = completed_items.drop(columns="_merge")`

이전에 데이터를 합칠 때 `indicator=True`를 사용해서  
`_merge`라는 확인용 컬럼이 만들어졌다.

이번에 다시 `merge`를 사용하면 `_merge` 컬럼이 또 만들어지기 때문에  
기존 `_merge` 컬럼을 먼저 삭제한다.

---

#### 2. products 데이터와 연결

`completed_items.merge(products, ...)`

완료된 주문 상품 데이터인 `completed_items`와  
상품 정보가 들어있는 `products`를 합친다.

---

#### 3. `on="product_id"`

두 데이터에 공통으로 존재하는 **product_id(상품 번호)**를 기준으로 연결한다.

예를 들어,

completed_items에 `product_id = 10`이 있다면  
products에서 `product_id = 10`인 상품을 찾아  
상품명과 카테고리 등의 정보를 붙여준다.

---

#### 4. `how="left"`

`completed_items`를 기준으로 데이터를 연결한다.

즉, **완료된 주문 상품은 그대로 유지하면서**
products에 있는 상품 정보를 가져온다.

---

#### 5. `validate="many_to_one"`

데이터가 우리가 예상한 관계로 연결되는지 검사한다.

주문 내역에서는 같은 상품이 여러 번 판매될 수 있기 때문에  
하나의 `product_id`가 여러 번 등장할 수 있다.

하지만 products에서는 하나의 `product_id`가  
하나의 상품을 나타내야 한다.

즉,

**여러 주문 상품 → 하나의 상품 정보**

관계가 맞는지 확인한다.

---

#### 6. `indicator=True`

데이터가 제대로 연결되었는지 확인하기 위해  
`_merge`라는 확인용 컬럼을 만든다.

- `both` : 양쪽 데이터에서 상품을 찾아 정상적으로 연결됨
- `left_only` : completed_items에는 있지만 products에서는 상품을 찾지 못함
- `right_only` : products에만 존재함

따라서 `_merge`를 확인하면 상품 정보가 제대로 연결되었는지 검증할 수 있다.

---

### 한 줄 정리

**완료된 주문 상품의 product_id를 이용해 products에서 상품명과 카테고리 등의 정보를 가져오고, 데이터가 올바르게 연결되었는지 함께 검사하는 코드이다.**

In [130]:
completed_items["_merge"].value_counts()

_merge
both          474
left_only       0
right_only      0
Name: count, dtype: int64